# Generated by Django 4.2.8 on 2024-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dcontacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonofijo', models.IntegerField()),
                ('telcelular', models.IntegerField()),
                ('celectronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ddomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=20)),
                ('codigopostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dpersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('fnacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
